config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :carts, :only => [:create, :destroy]
  end
  resources :carts, :only => [:index]
  devise_for :users
  root to: 'products#index'

  resources :charges


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include Filterable

  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "200x200>" }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  scope :brand, -> (brand) {where brand: brand}
  scope :category, -> (category) {where category: category}

  has_many :carts
  has_many :users, :through => :carts

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :carts
  has_many :products, :through => :carts

  # def empty_carts
  #   self.carts.each{|x| x.destroy}
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    total =0
    @user.carts.each {|x| total += x.product.price}
    @amount = total
  end

  def create
    @product = Product.find(params[:product_id])
    @user = current_user
    transaction = @user.carts.new({:product_id => @product.id})
    if transaction.save
      flash[:notice] = "#{@product.brand} #{@product.name} added to your cart."
      redirect_to :back
    else
      flash[:alert] = transaction.errors.messages
      redirect_to :back
    end
  end
  def destroy
    cart = Cart.find(params[:id])
    cart.destroy
    flash[:alert] = "removed from your cart"
    redirect_to carts_path
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new

  end

  def create
    # Amount in cents
    amount = params[:amount].to_i * 100
    # Create the customer in Stripe
    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      card: params[:stripeToken]
    )

    # Create the charge using the customer data returned by Stripe API
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: amount,
      description: 'Rails Stripe customer',
      currency: 'usd'
    )
    current_user.carts.each { |x| x.destroy }
    flash[:notice] = "Your card has been charged $#{params[:amount]}. Check yr e-mail for a receipt. Email dingdong@gmail.com if you have any questions :)"
    redirect_to root_path
   rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
    flash[:notice] = "Please try again brah"
  end




end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :is_admin?, except: [:index, :show]
  def is_admin?
    if current_user.admin
      current_user
    else
      flash[:alert] = "You don't have access."
      redirect_to root_path
    end
  end

  def index
    @products = Product.filter(params.slice(:brand, :category))
    @brands = @products.distinct.pluck(:brand)
    @selected_category = params[:category]
  end


  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :category, :brand, :price, :stock, :image)
    end
    def filtering_params(params)
      params.slice(:brand, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def total_price
    total = 0
    @user.carts.each {|x| total += x.product.price}
    total
  end
  def all_brands
    if @selected_category
      Product.where(category: @selected_category).distinct.pluck(:brand)
    else
      Product.all.distinct.pluck(:brand)
    end
  end
end

app/views/carts/index.html.erb
<div class="container">
  <div class="row">
    <h1><%= @user.name %>'s Cart</h1>

    <% @user.carts.each do |cart| %>
    <div class="col-sm-3">
      <%= image_tag cart.product.image.url(:thumb) %>
      <p><%= cart.product.name %></p>
      <p>Price: $<%= cart.product.price %></p>
      <%= link_to "Remove from cart", product_cart_path(cart.product, cart), :data => {:confirm => "For sure?",
        :method => "delete"} %>
    </div>
    <% end %>
    <h3>Cart Total: $<%= @amount %></h3>
  </div>
  <%= form_tag charges_path do -%>
   <article>
       <%= label_tag 'amount', 'To Pay', class: 'amount' %>
       <%= label_tag 'amount', "$#{@amount}", class: 'amount-figure' %>
       <%= hidden_field_tag 'amount', @amount %>
   </article>

   <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= ENV.fetch('PUBLISHABLE_KEY') %>"
      data-description="Your payment description"
      data-amount="<%= @amount * 100 %>">
    </script>
  <% end %>
</div>

app/views/carts/index.js.erb
<% current_user.carts.each{ |x| x.destroy }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Valhalla Sports</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= image_tag 'x.png', class: 'x' %>
          <h4 class="message"><%= value %></h4>
        </div>
      <% end %>
    </div>

    <div class="nav-wrap">
      <div class="container-fluid dark">
        <header class="container no-padding">
          <div class="row">
            <div class="col-sm-8 no-padding">
              <h1 class="logo"><%= link_to 'VALHALLA', root_path%></h1>
              <ul id="store-nav">
                <li><%= link_to "Products", products_path, id: 'products-path', remote: true %></li>



              </ul>
            </div>
            <div class="col-sm-4 no-padding">
              <ul id="user-nav">
                <% if current_user %>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %></li>
                <% else %>
                <li><%= link_to "Sign In", new_user_session_path %></li>
                <% end %>
                <% if current_user %>
                <li><%= link_to "Cart (#{current_user.carts.size})", carts_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </header>
      </div>
      <div class="container-fluid product-drop">
        <div class="container">
          <div class="row">
            <div class="col-sm-12 no-padding">
              <ul id="product-cat">
                <li><%= link_to "All", products_path %></li>
                <li><%= link_to "Boards", products_path(category: 'board') %></li>
                <li><%= link_to "Bindings", products_path(category: 'bindings') %></li>
                <li><%= link_to "Boots", products_path(category: 'boots') %></li>
                <li><%= link_to "Outerwear", products_path(category: 'outerwear') %></li>
                <li><%= link_to "Backcountry", products_path(category: 'backcountry') %></li>
                <li><%= link_to "Accessories", products_path(category: 'accessories') %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="main-content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :stock %>
    <%= f.number_field :stock %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">
  <ul id="product-sort">
    <% if params[:brand] %>
      <li><%= link_to "All #{@selected_category}", products_path(category: params[:category]) %></li>
    <% end %>
    <% all_brands.each do |b| %>
    <li><%= link_to b, products_path(brand: b, category: params[:category]) %></li>
    <% end %>
  </ul>
  <div class="row product-list-row">
    <% @products.each do |product| %>
      <div class="product-pane col-sm-4">
          <%= link_to image_tag(product.image.url(:thumb), class: 'center-block'), product %>
          <div class="col-sm-12 prod-title">
              <h4><%= link_to "#{product.brand} #{product.name}", product %></h4>
              <h4> $<%= link_to product.price, product_carts_path(product.id), method: 'post' %></h4>
          </div>
        <% if current_user && current_user.admin == true %>
          <%= link_to 'Edit', edit_product_path(product) %> |
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <% end %>
        </tr>
      </div>
    <% end %>
  </div>
  <% if current_user && current_user.admin == true %>
    <div class="row">
      <%= link_to 'New Product', new_product_path %>
    </div>
  <% end %>
</div>

app/views/products/index.js.erb
$('.product-drop').slideToggle();

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">
  <div class="row back-row">
    <%= link_to 'Back', products_path %>
  </div>
  <div class="row product-det-row">
    <div class="col-sm-5 product-detail-img">
      <%= image_tag @product.image.url(:medium) %>
    </div>
    <div class="col-sm-7 product-detail-info">
      <div class="info-wrap">
        <h1>
          <%= @product.name %>
        </h1>



        <p class="brand">
          <%= @product.brand %>
        </p>

        <p class="price">$
          <%= @product.price %>
        </p>
        <%= link_to "Add to cart", product_carts_path(@product.id), method: 'post', class: 'btn purchase'%>
      </div>
    </div>
  </div>
</div>